### ISSUE TITLE
关于IV的问题

### ISSUE THREAD

**Issue by Kiritomo** [hestyle/m3u8_downloader#2]
在初始化AES的时候，提示ValueError: Incorrect IV length (it must be 16 bytes long)，IV为0xa120a6138fb13f92cfad3051b53467d9，请问式什么原因？萌新一个，劳烦大佬解答

**Comment by hestyle** [comment]
IV长度不是16字节长度，看下你cryptor初始化的代码，

如果没有改动我的代码的话，调试到这一行，看下key.iv的值
cryptor = AES.new(bytes(keyText, encoding='utf8'), AES.MODE_CBC, bytes(key.iv, encoding='utf8'))

**Comment by liiyee** [comment]
说明你这个iv本身是加密的，这要参考js进行分析了
